matrix:
  include:
    - language: go
      go:
        - 1.14.x
      before_install:
        - cd golang/
      install:
        - . $HOME/.nvm/nvm.sh
        - nvm install 12
        - nvm use 12
      script:
        - make ci

    - language: node_js
      node_js:
        - 12
      before_install:
        - cd frontend/
      script:
        - make ci

notifications:
  email: false
