apiVersion: v1
kind: Service
metadata:
  name: club-backend-${ENV}-service
spec:
  selector:
    app: club-backend
    env: ${ENV}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
